# Generated by Django 3.2.9 on 2022-03-02 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20220228_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
